#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xBE793007AD22DF7E (tsujan2000@gmail.com)
#
Name     : lxqt-themes
Version  : 0.17.0
Release  : 6
URL      : https://github.com/lxqt/lxqt-themes/releases/download/0.17.0/lxqt-themes-0.17.0.tar.xz
Source0  : https://github.com/lxqt/lxqt-themes/releases/download/0.17.0/lxqt-themes-0.17.0.tar.xz
Source1  : https://github.com/lxqt/lxqt-themes/releases/download/0.17.0/lxqt-themes-0.17.0.tar.xz.asc
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.1
Requires: lxqt-themes-data = %{version}-%{release}
Requires: lxqt-themes-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : liblxqt-dev
BuildRequires : lxqt-build-tools

%description
Where did the pizza cutter go?
Right there!
https://github.com/Razor-qt/razor-qt/tree/master/razorqt-resources/graphics

%package data
Summary: data components for the lxqt-themes package.
Group: Data

%description data
data components for the lxqt-themes package.


%package license
Summary: license components for the lxqt-themes package.
Group: Default

%description license
license components for the lxqt-themes package.


%prep
%setup -q -n lxqt-themes-0.17.0
cd %{_builddir}/lxqt-themes-0.17.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1618499788
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1618499788
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/lxqt-themes
cp %{_builddir}/lxqt-themes-0.17.0/COPYING %{buildroot}/usr/share/package-licenses/lxqt-themes/7fab4cd4eb7f499d60fe183607f046484acd6e2d
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/icons/hicolor/scalable/apps/lxqt.svg
/usr/share/icons/hicolor/scalable/places/start-here-lxqt.svg
/usr/share/lxqt/graphics/README
/usr/share/lxqt/graphics/helix.svg
/usr/share/lxqt/graphics/helix_1120.png
/usr/share/lxqt/graphics/helix_150.png
/usr/share/lxqt/graphics/helix_60.png
/usr/share/lxqt/graphics/helix_lxqt.svg
/usr/share/lxqt/graphics/lxqt_logo.png
/usr/share/lxqt/graphics/lxqt_logo_doxygen.png
/usr/share/lxqt/graphics/spacer-dark-dots.svg
/usr/share/lxqt/graphics/spacer-dark-line.svg
/usr/share/lxqt/graphics/spacer-light-dots.svg
/usr/share/lxqt/graphics/spacer-light-line.svg
/usr/share/lxqt/themes/Clearlooks/arrow-right-selected.svg
/usr/share/lxqt/themes/Clearlooks/arrow-right.svg
/usr/share/lxqt/themes/Clearlooks/calendar-popup/left-arrow.svg
/usr/share/lxqt/themes/Clearlooks/calendar-popup/right-arrow.svg
/usr/share/lxqt/themes/Clearlooks/lxqt-notificationd.qss
/usr/share/lxqt/themes/Clearlooks/lxqt-notificationd/cancel.svg
/usr/share/lxqt/themes/Clearlooks/lxqt-panel.qss
/usr/share/lxqt/themes/Clearlooks/lxqt-runner.qss
/usr/share/lxqt/themes/Clearlooks/lxqt-runner/close.svg
/usr/share/lxqt/themes/Clearlooks/lxqt-runner/down-arrow.svg
/usr/share/lxqt/themes/Clearlooks/mainmenu.svg
/usr/share/lxqt/themes/Clearlooks/preview.png
/usr/share/lxqt/themes/Clearlooks/spacer-plugin/spacer-dots.svg
/usr/share/lxqt/themes/Clearlooks/spacer-plugin/spacer-line.svg
/usr/share/lxqt/themes/Leech/arrow-right.svg
/usr/share/lxqt/themes/Leech/calendar-popup/left-arrow.svg
/usr/share/lxqt/themes/Leech/calendar-popup/right-arrow.svg
/usr/share/lxqt/themes/Leech/lxqt-notificationd.qss
/usr/share/lxqt/themes/Leech/lxqt-notificationd/cancel.svg
/usr/share/lxqt/themes/Leech/lxqt-panel.qss
/usr/share/lxqt/themes/Leech/lxqt-runner.qss
/usr/share/lxqt/themes/Leech/lxqt-runner/close.svg
/usr/share/lxqt/themes/Leech/lxqt-runner/down-arrow.svg
/usr/share/lxqt/themes/Leech/mainmenu.svg
/usr/share/lxqt/themes/Leech/preview.png
/usr/share/lxqt/themes/Leech/spacer-plugin/spacer-dots.svg
/usr/share/lxqt/themes/Leech/spacer-plugin/spacer-line.svg
/usr/share/lxqt/themes/ambiance/Butterfly-Kenneth-Wimer.jpg
/usr/share/lxqt/themes/ambiance/arrow-left.svg
/usr/share/lxqt/themes/ambiance/arrow-right.svg
/usr/share/lxqt/themes/ambiance/lxqt-notificationd.qss
/usr/share/lxqt/themes/ambiance/lxqt-notificationd/cancel.svg
/usr/share/lxqt/themes/ambiance/lxqt-panel.qss
/usr/share/lxqt/themes/ambiance/lxqt-runner.qss
/usr/share/lxqt/themes/ambiance/lxqt-runner/clear.svg
/usr/share/lxqt/themes/ambiance/lxqt-runner/navigation-menu.svg
/usr/share/lxqt/themes/ambiance/mainmenu.svg
/usr/share/lxqt/themes/ambiance/preview.png
/usr/share/lxqt/themes/ambiance/spacer-plugin/spacer-dots.svg
/usr/share/lxqt/themes/ambiance/spacer-plugin/spacer-line.svg
/usr/share/lxqt/themes/ambiance/wallpaper.cfg
/usr/share/lxqt/themes/dark/arrow-right.svg
/usr/share/lxqt/themes/dark/calendar-popup/left-arrow.svg
/usr/share/lxqt/themes/dark/calendar-popup/right-arrow.svg
/usr/share/lxqt/themes/dark/checked.svg
/usr/share/lxqt/themes/dark/lxqt-notificationd.qss
/usr/share/lxqt/themes/dark/lxqt-notificationd/cancel.svg
/usr/share/lxqt/themes/dark/lxqt-panel.qss
/usr/share/lxqt/themes/dark/lxqt-runner.qss
/usr/share/lxqt/themes/dark/lxqt-runner/close.svg
/usr/share/lxqt/themes/dark/lxqt-runner/down-arrow.svg
/usr/share/lxqt/themes/dark/mainmenu.svg
/usr/share/lxqt/themes/dark/preview.png
/usr/share/lxqt/themes/dark/spacer-plugin/spacer-dots.svg
/usr/share/lxqt/themes/dark/spacer-plugin/spacer-line.svg
/usr/share/lxqt/themes/dark/unchecked.svg
/usr/share/lxqt/themes/dark/wallpaper.cfg
/usr/share/lxqt/themes/dark/wallpaper.png
/usr/share/lxqt/themes/frost/arrow-right.svg
/usr/share/lxqt/themes/frost/calendar-popup/left-arrow.svg
/usr/share/lxqt/themes/frost/calendar-popup/right-arrow.svg
/usr/share/lxqt/themes/frost/color-picker.svg
/usr/share/lxqt/themes/frost/debug.png
/usr/share/lxqt/themes/frost/lxqt-notificationd.qss
/usr/share/lxqt/themes/frost/lxqt-origami-light.png
/usr/share/lxqt/themes/frost/lxqt-panel.qss
/usr/share/lxqt/themes/frost/lxqt-runner.qss
/usr/share/lxqt/themes/frost/lxqt-runner/close.svg
/usr/share/lxqt/themes/frost/lxqt-runner/down-arrow.svg
/usr/share/lxqt/themes/frost/mainmenu.svg
/usr/share/lxqt/themes/frost/preview.png
/usr/share/lxqt/themes/frost/spacer-plugin/spacer-dots.svg
/usr/share/lxqt/themes/frost/spacer-plugin/spacer-line.svg
/usr/share/lxqt/themes/frost/volume-plugin/mixer.svg
/usr/share/lxqt/themes/frost/wallpaper.cfg
/usr/share/lxqt/themes/kde-plasma/kde-plasma.png
/usr/share/lxqt/themes/kde-plasma/left-arrow.svg
/usr/share/lxqt/themes/kde-plasma/lxqt-notificationd.qss
/usr/share/lxqt/themes/kde-plasma/lxqt-notificationd/window-close.svg
/usr/share/lxqt/themes/kde-plasma/lxqt-panel.qss
/usr/share/lxqt/themes/kde-plasma/lxqt-runner.qss
/usr/share/lxqt/themes/kde-plasma/lxqt-runner/application-menu.svg
/usr/share/lxqt/themes/kde-plasma/lxqt-runner/close-32x32.png
/usr/share/lxqt/themes/kde-plasma/lxqt-runner/close-48x48.png
/usr/share/lxqt/themes/kde-plasma/lxqt-runner/window-close.svg
/usr/share/lxqt/themes/kde-plasma/mainmenu.svg
/usr/share/lxqt/themes/kde-plasma/preview.png
/usr/share/lxqt/themes/kde-plasma/right-arrow.svg
/usr/share/lxqt/themes/kde-plasma/spacer-plugin/spacer-dots.svg
/usr/share/lxqt/themes/kde-plasma/spacer-plugin/spacer-line.svg
/usr/share/lxqt/themes/kde-plasma/wallpaper.cfg
/usr/share/lxqt/themes/kvantum/lxqt-config.qss
/usr/share/lxqt/themes/kvantum/lxqt-notificationd.qss
/usr/share/lxqt/themes/kvantum/lxqt-panel.qss
/usr/share/lxqt/themes/kvantum/lxqt-panel/arrow-left-selected.svg
/usr/share/lxqt/themes/kvantum/lxqt-panel/arrow-left.svg
/usr/share/lxqt/themes/kvantum/lxqt-panel/arrow-right-selected.svg
/usr/share/lxqt/themes/kvantum/lxqt-panel/arrow-right.svg
/usr/share/lxqt/themes/kvantum/lxqt-panel/checked.svg
/usr/share/lxqt/themes/kvantum/lxqt-panel/mainmenu.svg
/usr/share/lxqt/themes/kvantum/lxqt-panel/plugin-handle-horizontal.svg
/usr/share/lxqt/themes/kvantum/lxqt-panel/plugin-handle-vertical.svg
/usr/share/lxqt/themes/kvantum/lxqt-panel/radio-checked.svg
/usr/share/lxqt/themes/kvantum/lxqt-panel/radio-unchecked.svg
/usr/share/lxqt/themes/kvantum/lxqt-panel/unchecked.svg
/usr/share/lxqt/themes/kvantum/lxqt-runner.qss
/usr/share/lxqt/themes/kvantum/lxqt-runner/close.svg
/usr/share/lxqt/themes/kvantum/lxqt-runner/down.svg
/usr/share/lxqt/themes/kvantum/preview.png
/usr/share/lxqt/themes/kvantum/spacer-plugin/spacer-dots.svg
/usr/share/lxqt/themes/kvantum/spacer-plugin/spacer-line.svg
/usr/share/lxqt/themes/light/96640-simple_blue_widescreen.svg
/usr/share/lxqt/themes/light/lxqt-lightdm-greeter/dropdown.svg
/usr/share/lxqt/themes/light/lxqt-lightdm-greeter/leaveIcon.svg
/usr/share/lxqt/themes/light/lxqt-notificationd.qss
/usr/share/lxqt/themes/light/lxqt-panel.qss
/usr/share/lxqt/themes/light/lxqt-panel/plugin-handle-horizontal.gif
/usr/share/lxqt/themes/light/lxqt-panel/plugin-handle-vertical.gif
/usr/share/lxqt/themes/light/lxqt-runner.qss
/usr/share/lxqt/themes/light/lxqt-runner/close-32x32.png
/usr/share/lxqt/themes/light/lxqt-runner/close-48x48.png
/usr/share/lxqt/themes/light/mainmenu.svg
/usr/share/lxqt/themes/light/preview.png
/usr/share/lxqt/themes/light/simple_blue_widescreen.png
/usr/share/lxqt/themes/light/spacer-plugin/spacer-dots.svg
/usr/share/lxqt/themes/light/spacer-plugin/spacer-line.svg
/usr/share/lxqt/themes/light/wallpaper.cfg
/usr/share/lxqt/themes/system/lxqt-panel.qss
/usr/share/lxqt/themes/system/preview.png
/usr/share/lxqt/themes/system/spacer-plugin/spacer-dots.svg
/usr/share/lxqt/themes/system/spacer-plugin/spacer-line.svg

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/lxqt-themes/7fab4cd4eb7f499d60fe183607f046484acd6e2d
